# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce182fc30983d85dc9d20ab42b62e5f5add360580eb2cfe455e7d9209efe67931bc49f2daee21cf520a203993df157f1463bbf00afca87a342cd206be8ec54b2

test:
  secret_key_base: 585780aea05eebadd34361f85b108016b1d14655149fcb2eacc9f1b6f86778ef004c4b176328f19536eb645c58b7dfce80042088239a6b6e83eb0688e24d72f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
